# Generated by Django 4.0.3 on 2022-04-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/placeholder.img', null=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
