# Generated by Django 4.0.3 on 2022-04-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='StockQuantity',
        ),
    ]
