# Generated by Django 4.0.3 on 2022-04-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_quantity_product_stockquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='StockQuantity',
        ),
        migrations.AddField(
            model_name='product',
            name='stockQuantity',
            field=models.IntegerField(default=1, verbose_name='Количество на складе'),
        ),
    ]
