# Generated by Django 4.0.3 on 2022-04-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_stockquantity_product_stockquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
    ]
